GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Harry Potter",
    "number": 911
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Harry Potter",
    "number": 911
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Harry Potter"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": 911
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

###
DELETE http://localhost:3001/api/persons/68e0e0f5451ce594a8de4541

###
DELETE http://localhost:3001/api/persons/4

