GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXIxIiwiaWQiOiI2OTI2YzQyN2JlZGRlNGUwNTUzYmIzMmEiLCJpYXQiOjE3NjQxNDgyNjR9.dJGkLxU9OW7vzVZcWsJlachphiDoqUlgukcps343yX8

{
    "title": "Hannah's Travels",
    "author": "Hannah Kirk",
    "url": "https://hannahs-travels.com",
    "likes": 2
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "User1",
    "name": "User 1",
    "password": "Password"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "User1",
    "password": "Password"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "User1",
    "password": "Passwords"
}


###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Us",
    "name": "User 1",
    "password": "Password"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "User1A",
    "name": "User 1",
    "password": null
}

