GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXIxIiwiaWQiOiI2OTI2Y2MzZjI0MDJmODlhNjVjMzRlMzUiLCJpYXQiOjE3NjQxNTAzMzh9.rHyLxGoAkJriI8T1ghbRn3nslJG0ABKwuFhccXjq--k

{
    "title": "Hannah's Travels",
    "author": "Hannah Kirk",
    "url": "https://hannahs-travels.com",
    "likes": 2
}

###
DELETE http://localhost:3003/api/blogs/6926c8cea64699ee7ad7da18
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXIyIiwiaWQiOiI2OTI2YzhiNWE2NDY5OWVlN2FkN2RhMGUiLCJpYXQiOjE3NjQxNDk0Njl9.8BwOMJK9Prl7I4sr2yAp3QZhWsMVzCzLImTKCakROHo

{
    "title": "Hannah's Travels",
    "author": "Hannah Kirk",
    "url": "https://hannahs-travels.com",
    "likes": 2
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "User1",
    "name": "User 1",
    "password": "Password"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "User2",
    "name": "User 2",
    "password": "Password"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "User1",
    "password": "Password"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "User2",
    "password": "Password"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "User1",
    "password": "Passwords"
}


###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Us",
    "name": "User 1",
    "password": "Password"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "User1A",
    "name": "User 1",
    "password": null
}

